//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AccountDTO {
    username?: string;
    fullName?: string;
    address?: string;
    phone?: string;
    email?: string;
    otherContact?: string;
    description?: string;
    avatar?: string;
    role?: string;
    functions?: string[];
    state?: string;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;

    [key: string]: any;
}

export interface BlogDTO {
    id?: string;
    title?: string;
    content?: string;
    coverPhoto?: string;
    tags?: string[];
    amountOfAccesses?: number;
    state?: number;
    publishedAt?: string | undefined;
    likedByUser?: boolean | undefined;
    authorId?: string;
    authorName?: string;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;

    [key: string]: any;
}

export interface BlogLikeDTO {
    authorId?: string;
    blogId?: string;
    likeOrNot?: boolean;

    [key: string]: any;
}

export interface BlogListRespDTO {
    datas?: BlogDTO[];
    statusCode?: number;
    message?: string;

    [key: string]: any;
}

export interface BlogPageRespDTO {
    statusCode?: number;
    message?: string;

    [key: string]: any;
}

export interface CommentDTO {
    id?: string;
    content?: string;
    state?: number;
    likedByUser?: boolean | undefined;
    authorId?: string;
    blogId?: string;
    parentId?: string | undefined;
    createdAt?: string | undefined;

    [key: string]: any;
}

export interface CommentLikeDTO {
    authorId?: string;
    commentId?: string;
    likeOrNot?: boolean;

    [key: string]: any;
}

export interface LoginDTO {
    username?: string;
    password?: string;

    [key: string]: any;
}

export interface LoginRespDTO {
    jwt: string;
    statusCode?: number;
    message?: string;

    [key: string]: any;
}

export interface NotificationDTO {
    content?: string;
    targetType?: string;
    targetId?: string;
    createdAt?: string | undefined;
    receiverId?: string;

    [key: string]: any;
}

export interface PageDTO<T> {
    datas?: T[];
    curPage?: number;
    pageSize?: number;

    [key: string]: any;
}

export interface RegisterDTO {
    username?: string;
    password?: string;
    fullName?: string;
    address?: string;
    phone?: string;
    email?: string;
    otherContact?: string;
    description?: string;

    [key: string]: any;
}

export interface RegisterRespDTO {
    account?: AccountDTO;
    statusCode?: number;
    message?: string;

    [key: string]: any;
}

export interface ReportDTO {
    id?: string;
    targetType?: string;
    targetId?: string;
    content?: string;
    reporterId?: string;
    createdAt?: string | undefined;

    [key: string]: any;
}

export interface ReqDTO {
    page?: number;

    [key: string]: any;
}

export interface RespDTO {
    statusCode?: number;
    message?: string;

    [key: string]: any;
}

export interface SearchBlogReqDTO {
    searchTitle?: string;
    categories?: string[];
    searchFlag?: number;
    curPage?: number;

    [key: string]: any;
}

export interface SearchBlogRespDTO {
    blogs: PageDTO<BlogDTO>;
    statusCode?: number;
    message?: string;

    [key: string]: any;
}

export interface TagDTO {
    name?: string;
    description?: string;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;

    [key: string]: any;
}

export interface TagListRespDTO {
    datas?: TagDTO[];
    statusCode?: number;
    message?: string;

    [key: string]: any;
}