//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AccountDTO {
    username?: string;
    fullName?: string;
    address?: string;
    phone?: string;
    email?: string;
    otherContact?: string;
    description?: string;
    avatar?: string;
    role?: string;
    functions?: string[];
    state?: string;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;

    [key: string]: any;
}

export interface AuthenEmailReqDTO {
    email?: string;

    [key: string]: any;
}

export interface AuthenEmailRespDTO {
    sessionId?: string;

    [key: string]: any;
}

export interface BlogDTO {
    id?: string | undefined;
    title?: string;
    content?: string;
    coverImage?: string | undefined;
    tags?: string[];
    amountOfAccesses?: number | undefined;
    state?: number;
    publishedAt?: string | undefined;
    likedByUser?: boolean | undefined;
    authorId?: string;
    authorName?: string | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;

    [key: string]: any;
}

export interface BlogLikeDTO {
    authorId?: string;
    blogId?: string;
    likeOrNot?: boolean;

    [key: string]: any;
}

export interface CommentDTO {
    id?: string;
    content?: string;
    state?: number;
    likedByUser?: boolean | undefined;
    authorId?: string;
    blogId?: string;
    parentId?: string | undefined;
    createdAt?: string | undefined;

    [key: string]: any;
}

export interface CommentLikeDTO {
    authorId?: string;
    commentId?: string;
    likeOrNot?: boolean;

    [key: string]: any;
}

export interface ErrorRespDTO {
    message: string;

    [key: string]: any;
}

export interface LoginReqDTO {
    username?: string;
    password?: string;

    [key: string]: any;
}

export interface LoginRespDTO {
    token: string;

    [key: string]: any;
}

export interface NotificationDTO {
    content?: string;
    targetType?: string;
    targetId?: string;
    createdAt?: string | undefined;
    receiverId?: string;

    [key: string]: any;
}

export interface RegisterReqDTO {
    username?: string;
    password?: string;
    fullName?: string;
    email?: string;

    [key: string]: any;
}

export interface ReportDTO {
    id?: string;
    targetType?: string;
    targetId?: string;
    content?: string;
    reporterId?: string;
    createdAt?: string | undefined;

    [key: string]: any;
}

export interface RequestBaseDTOOfAuthenEmailReqDTO {
    datas?: AuthenEmailReqDTO | undefined;
    base64Strings?: string[] | undefined;

    [key: string]: any;
}

export interface RequestBaseDTOOfBlogDTO {
    datas?: BlogDTO | undefined;
    base64Strings?: string[] | undefined;

    [key: string]: any;
}

export interface RequestBaseDTOOfLoginReqDTO {
    datas?: LoginReqDTO | undefined;
    base64Strings?: string[] | undefined;

    [key: string]: any;
}

export interface RequestBaseDTOOfSearchBlogReqDTO {
    datas?: SearchBlogReqDTO | undefined;
    base64Strings?: string[] | undefined;

    [key: string]: any;
}

export interface RequestBaseDTOOfVerifyEmailOTPReqDTO {
    datas?: VerifyEmailOTPReqDTO | undefined;
    base64Strings?: string[] | undefined;

    [key: string]: any;
}

export interface SearchBlogReqDTO {
    searchTitle?: string | undefined;
    tags?: string[] | undefined;
    searchFlag?: number;
    curPage?: number;

    [key: string]: any;
}

export interface TagDTO {
    name?: string;
    description?: string;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;

    [key: string]: any;
}

export interface VerifyEmailOTPReqDTO {
    sessionId?: string;
    otp?: string;

    [key: string]: any;
}

export interface Body {
    "Datas.Username"?: string;
    "Datas.Password"?: string;
    "Datas.FullName"?: string;
    "Datas.Email"?: string;
    Base64Strings?: string[];

    [key: string]: any;
}